### ISSUE TITLE
Cannot open http://mirror.de-labrusse.fr

### ISSUE THREAD

**Issue by dutch55** [stephdl/nethserver-ddclient#2]
I tried executing the commands, got an error "cannot open"

[root@yashi ~]# yum install http://mirror.de-labrusse.fr/NethServer/6/noarch/net                                  hserver-stephdl-1.0.0-1.ns6.noarch.rpm
Loaded plugins: changelog, fastestmirror, nethserver_events, presto
Setting up Install Process
Cannot open: http://mirror.de-labrusse.fr/NethServer/6/noarch/nethserver-stephdl                                  -1.0.0-1.ns6.noarch.rpm. Skipping.

**Comment by stephdl** [comment]
hi

the documentation is not uptodate, firstable you must use the dzoote repo

http://wiki.nethserver.org/doku.php?id=howto:dz00te_repo_howto

then you can install rpm from this repository

**Comment by stephdl** [comment]
closed as the stephdl repo is now reopened
