### ISSUE TITLE
Support for MultiWAN

### ISSUE THREAD

**Issue by lockheed** [stephdl/nethserver-ddclient#4]
Please, add MultiWAN support. DDclient is of no use if every 300 seconds it changes the associated ip because it goes out through different WAN connection.

**Comment by stephdl** [comment]
right, that need to set just one NIC to watch....do you see something relevant in the ddclient settings ?

**Comment by lockheed** [comment]
No. The settings there are quite limited. I set it up,  but it randomly goes through different WANs. I tried fixing it by Firewall routing rulls (traffic to IP of ddns provider (firewall object) is redirected to WLAN1) but it does not seem to work. IP still randomly changes between both WANs.

**Comment by stephdl** [comment]
please can you  give me the output of 

`db networks show`

We could have something workable if we don't use the 'web'  but the 'if' protocol.
Something like this could work

```

daemon=300
syslog=yes
mail-failure=youremail@nospamwanted.com
cache=/var/cache/ddclient/ddclient.cache
pid=/var/run/ddclient.pid
ssl=yes
syslog=yes
use=if
if=eth0
server=members.dyndns.org 
protocol=dyndns2 
login=your_username
password=your_password
yourhost1.dyndnsdomain.org
use=if
if=eth1
server=members.dyndns.org
protocol=dyndns2
login=your_username
password=your_password
yourhost2.dyndnsdomain.org
```
however in this case the ddclient will look just after one IP, not the rescue one on the other NIC

**Comment by lockheed** [comment]
Here is the output:

> # db networks show
> Asus=provider
>     interface=enp0s25.4
>     weight=75
> Netia=provider
>     interface=enp0s25
>     weight=100
> enp0s25=ethernet
>     FwInBandwidth=
>     FwOutBandwidth=
>     bootproto=dhcp
>     gateway=
>     ipaddr=192.168.24.166
>     netmask=255.255.255.0
>     role=red
> enp0s25.2=vlan
>     bootproto=none
>     gateway=
>     ipaddr=192.168.24.1
>     netmask=255.255.255.0
>     role=green
> enp0s25.4=vlan
>     FwInBandwidth=
>     FwOutBandwidth=
>     bootproto=none
>     gateway=192.168.100.1
>     ipaddr=192.168.100.2
>     netmask=255.255.255.0
>     role=red
> ens2=ethernet
>     role=
> ppp0=xdsl-disabled
>     AuthType=auto
>     FwInBandwidth=
>     FwOutBandwidth=
>     Password=
>     name=PPPoE
>     provider=xDSL provider
>     role=red
>     user=

**Comment by stephdl** [comment]
the multiwan is not managed by NS, you seem to get a modem or a router in front of each network interface ?
I suppose that they are not bridged...I said that because I don't see Internet IP, only lan IP (192.168.100.2,192.168.24.1). I can have further investigation but I woryy if the IP mode/router is not bridged to your NIC, then ddclient won't see the changes.

BTW why have you closed this thread ?

**Comment by lockheed** [comment]
This is correct, the WAN connections are behind NATs. However, I was under the impression that ddclient built into NS does not get the IP from the host it is running on, but by querying an external source (like checkip.dyndns.org) to get the IP it is seen as by it. I take this view because of what I see in the "DdClient Service Settings" tab of the module in NS.
Am I wrong?

Apologies for closing the thread, I was unaware I did this.

**Comment by lockheed** [comment]
Ok, I set one of the WAN addresses to get the direct IP from ISP. What can I do now to make ddhclient use this IP?

By the way: I think I found a bug in NethServer, although maybe I'm wrong. 
Take a look at what happens if I change DHCP from ethernet port to a bridge of pppoe type:

>  # db networks show
> Asus=provider
>     interface=enp0s25.4
>     weight=75
> Netia=provider
>     interface=ppp0
>     weight=100
> enp0s25=ethernet
>     FwInBandwidth=
>     FwOutBandwidth=
>     role=pppoe
> enp0s25.2=vlan
>     bootproto=none
>     gateway=
>     ipaddr=192.168.24.1
>     netmask=255.255.255.0
>     role=green
> enp0s25.4=vlan
>     FwInBandwidth=
>     FwOutBandwidth=
>     bootproto=none
>     gateway=192.168.100.1
>     ipaddr=192.168.100.2
>     netmask=255.255.255.0
>     role=red
> ens2=ethernet
>     role=
> ppp0=xdsl
>     AuthType=auto
>     FwInBandwidth=
>     FwOutBandwidth=
>     Password=xxxxxx
>     name=PPPoE
>     provider=Netia
>     role=red
>     user=xxxx@xxx.xx

The problem is that Neth Server does not see the IP of the ppp interface, even though the IP is set and  ifconfig shows it:

> # ifconfig 
> enp0s25: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
> 
> enp0s25.2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.24.1  netmask 255.255.255.0  broadcast 192.168.24.255
> 
> enp0s25.4: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.100.2  netmask 255.255.255.0  broadcast 192.168.100.255
> 
> ppp0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1492
>         inet 159.205.209.99  netmask 255.255.255.255  destination 83.238.252.35
>

**Comment by lockheed** [comment]
Ok, I got this to run by removing nethserver-ddclient and using bare ddclient with 
`use=if, if=ppp0`
However, I think it would be beneficial if that functionality was present in the GUI version

**Comment by stephdl** [comment]
nice to know....can you explain me how works your network, how many internet links get your server....I have something that I don't understand.
What is connected to 
ppp0
enp0s25.2
enp0s25.4

Once understood I can do the UI

**Comment by stephdl** [comment]
> This is correct, the WAN connections are behind NATs. However, I was under the impression that ddclient built into NS does not get the IP from the host it is running on, but by querying an external source (like checkip.dyndns.org) to get the IP it is seen as by it. I take this view because of what I see in the "DdClient Service Settings" tab of the module in NS.
> Am I wrong?

No you are right, ddclient looks an external service periodically to see if the IP changes. If you think that you found a bug, please direct your question to community.nethserver.org. It is better to speak about something strange, rather to let a bug alive.

**Comment by lockheed** [comment]
My setup is probably somewhat atypical, so let me explain:

> enp0s25 - is the only physical NIC in use on this machine. It divides into VLANs:
> enp0s25.2 - green LAN
> enp0s25.4 - secondary WAN (it has a local IP, because it gets its IP as a client of an ASUS GSM router. This is because NethServer has non-existent support for USB GSM modems)
> ppp0 - this is a PPPoE bridged to enp0s25, getting the IP directly from the ISP. This is primary WAN.

Now, I solved the ddclient problem manually, as explained above. But ideally, apart from this functionality, it would be also good to see an option to have independent ddclients running on separate WANs, renewing "publicIP-domain" pairs for different ISPs on the same machine.

**Comment by stephdl** [comment]
thank

So if the wan on ppp0 fails, then you won't signal to ddclient you have changed your IP....can you test to see if ddclient gets another IP from your GSM gateway ?

**Comment by lockheed** [comment]
I am not sure I understand what are you asking.

**Comment by stephdl** [comment]
Simply, If you lost the internet connection from PPP0, do you update the new IP from your gsm gateway to your dynamic dns provider.
