### ISSUE TITLE
issue with namecheap

### ISSUE THREAD

**Issue by JOduMonT** [stephdl/nethserver-ddclient#7]
Hi Stephane;

it's not a big deal but I believe ddclient is not working properly with namecheap.com

when I use the web interface to configure ddclient it return an error because it is always looking for the @ of the domain, while if use 30Custom it works

### ddclient.conf with config via the web configurator
> server=dynamicdns.park-your-domain.com, \
> protocol=namecheap, \
> login=MyDomain.tld, \
> password=MyAPIPassword \
> @

### ddclient.conf with 30Custom
> server=dynamicdns.park-your-domain.com, \
> protocol=namecheap, \
> login=MyDomain.tld, \
> password=MyAPIPassword \
> subdomain1

**Comment by stephdl** [comment]
reading this https://www.namecheap.com/support/knowledgebase/article.aspx/583/11/how-do-i-configure-ddclient (check the comments)

```
login=mydomain.net
password='ddns_password_for_mydomain.net'
@.mydomain.net
```

the @needs to be used with the domain : @.MyDomain.tld

Could you test it please

**Comment by JOduMonT** [comment]
From what I understood @.mydomain.net is for the root domain
since the root of my domain is my website and it is hosted somewhere else (Netlify)
I don't want to redirect it on my home server.
But as I said it's works with 30Custom, so I'm fine with that option

**Comment by stephdl** [comment]
In short my question is how to determine what is the domain you want to update the dynamic dns, do it is the same than `login`

**Comment by JOduMonT** [comment]
> In short my question is how to determine what is the domain you want to update the dynamic dns, do it is the same than `login`

_Sorry I don't really understand._

The login I use is my domain.tld as mentioned in [namecheap documentation](https://www.namecheap.com/support/knowledgebase/article.aspx/583/11/how-do-i-configure-ddclient)
but also, namecheap only ask/require to declare the subdomain such as
```
login=mydomain.net
password='ddns_password_for_mydomain.net'
@,subdomain1,subdomain2
```
and not
```

login=mydomain.net
password='ddns_password_for_mydomain.net'
@.mydomain.net,subdomain1.mydomain.net,subdomain2.mydomain.net
```

**Comment by stephdl** [comment]
ok so you want to use a dyndns  only to the subdomain and not to the root domain (this is what you explained at the top)

Yes I wonder if it is not a corner case that only a fragment could cover

**Comment by JOduMonT** [comment]
> ok so you want to use a dyndns only to the subdomain and not to the root domain (this is what you explained at the top)

You understood very well on that ;)

> Yes I wonder if it is not a corner case that only a fragment could cover

As I said, it's work well with the 30Custom which it's fine for me because in anyway I could put multiple subdomain on one line

**Comment by stephdl** [comment]
thank for your time and explanations
